" Begin plugin system
call plug#begin('~/.vim/plugged')

" Dracula theme
Plug 'dracula/vim'

" Sensible Vim configuration
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-unimpaired'

" FZF plugin outside ~/.vim/plugged with post-update hook
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }

" On-demand loading of nerdtree
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
map <C-n> :NERDTreeToggle<CR>

" Bufferline
Plug 'bling/vim-bufferline'

" JavaScript
Plug 'pangloss/vim-javascript'
Plug 'mxw/vim-jsx'
Plug 'leshill/vim-json'
let g:jsx_ext_required = 0

" General coding
Plug 'editorconfig/editorconfig-vim'

" Initialize plugin system
call plug#end()

" Tabs are 2 spaces
set expandtab
set tabstop=2
set shiftwidth=2
" Round indent to multiple of 'shiftwidth'
set shiftround
" Smart indenting when starting a new line
set smartindent
" Copy indent from current line, over to the new line
set autoindent
" load filetype-specific indent files
filetype indent on

" show line numbers
set number
" show last command in bottom bar
set showcmd
" highlight cursor line
set cursorline
" highlight column at 80 characters
set cc=80
set wildignore=log/**,node_modules/**/**
" visual autocomplete for command menu
set wildmenu
" redraw only when we need to.
set lazyredraw
" highlight matching [{()}]
set showmatch
" show trailing whitespace
set list

" keyboard shortcuts
let mapleader=";"

" search as characters are entered
set incsearch
" highlight matches
set hlsearch
" case-insensitive search
set ignorecase
" case-sensitive search if any caps
set smartcase
" show context above/below cursorline
set scrolloff=3

" Enable basic mouse behavior
set mouse=a
" Support resizing in tmux
if exists('$TMUX')
  set ttymouse=xterm2
endif

" Set dark background
set background=dark

" Move vertically by visual line
nnoremap j gj
nnoremap k gk
